print("Hello, my name is Daren")
print("Hola, mi nombre es Daren")
print("Bonjour, je m'appelle Daren")
print("Hallo, mein Name ist Daren")
print("Ciao, mi chiamo Daren")
print("Olá, meu nome é Daren")
print("Hallo, mijn naam is Daren")
print("Привет, меня зовут Дарен")
print("你好，我的名字是达伦")
print("こんにちは、私の名前はダレンです")
print("안녕하세요, 제 이름은 다렌입니다")
print("مرحباً، اسمي دارين")
print("नमस्ते, मेरा नाम डैरेन है")
print("Salve, nomen meum est Daren")
