puts "Hello, my name is Daren"
puts "Hola, mi nombre es Daren"
puts "Bonjour, je m'appelle Daren"
puts "Hallo, mein Name ist Daren"
puts "Ciao, mi chiamo Daren"
puts "Olá, meu nome é Daren"
puts "Hallo, mijn naam is Daren"
puts "Привет, меня зовут Дарен"
puts "你好，我的名字是达伦"
puts "こんにちは、私の名前はダレンです"
puts "안녕하세요, 제 이름은 다렌입니다"
puts "مرحباً، اسمي دارين"
puts "नमस्ते, मेरा नाम डैरेन है"
puts "Salve, nomen meum est Daren"
