console.log("Hello, my name is The3DP");
console.log("Hola, mi nombre es The3DP");
console.log("Bonjour, je m'appelle The3DP");
console.log("Hallo, mein Name ist The3DP");
console.log("Ciao, mi chiamo The3DP");
console.log("Olá, meu nome é The3DP");
console.log("Hallo, mijn naam is The3DP");
console.log("Привет, меня зовут Дарен");
console.log("你好，我的名字是达伦");
console.log("こんにちは、私の名前はダレンです");
console.log("안녕하세요, 제 이름은 다렌입니다");
console.log("مرحباً، اسمي دارين");
console.log("नमस्ते, मेरा नाम डैरेन है");
console.log("Salve, nomen meum est The3DP");
